version: "3.8"
services: 
  bloodhound:
    build: bloodhound
    env_file:
      - .env
    environment: 
      - admin_user=admin
      - admin_password=password
      - admin_email=admin@localhost
    depends_on: 
      - db
    volumes: 
      - static:/static
  db:
    image: postgres
    env_file:
      - .env
  proxy:
    image: nginx
    ports: 
      - 80:80
    depends_on: 
      - bloodhound
    volumes: 
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static:/usr/share/nginx/html/static

volumes: 
  static: {}

